# Generated by Django 6.1 on 2026-09-08 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('database', 'Database'), ('tool', 'Tool')], default='language', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('image', models.CharField(blank=True, max_length=225, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web'), ('desain', 'Desain')], default='web', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(),
        ),
    ]
