# Generated by Django 5.2.17 on 2026-09-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expertise_project_alter_experience_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
    ]
